In [2]:
import numpy as np

In [3]:
b = [[1,2],[1,4],[3,2],[5,2],[8,9],[10,10]]
b = np.array(b)
a = np.random.choice(len(b),3,replace = False)
print(a)
c = [b[x] for x in a]
c

[1 2 5]


[array([1, 4]), array([3, 2]), array([10, 10])]

In [4]:
samples,features = b.shape
print(f"Samples:{samples}\nFearures:{features}")

Samples:6
Fearures:2


In [5]:
for x,y in enumerate(c):
    print(f"{x}\n{y}")

0
[1 4]
1
[3 2]
2
[10 10]


In [6]:
def dist(x1,x2):
    x1 = np.array(x1)
    x2 = np.array(x2)
    return np.sqrt(np.sum((x1-x2)**2))

dist([4,4],[4,6])

2.0

In [7]:
dataset = [_ for _ in range(100)]
choices = np.random.choice(len(dataset),3, replace=False)
display(choices)
choosen = [dataset[_] for _ in choices]
display(choosen)

array([47, 48, 37])

[47, 48, 37]

In [8]:
np.int0(np.zeros((5,2)))

array([[0, 0],
       [0, 0],
       [0, 0],
       [0, 0],
       [0, 0]], dtype=int64)

In [10]:
e = np.array(b)
np.mean(e, axis=0)

array([4.66666667, 4.83333333])

In [13]:
np.mean([[1,2],[3,4]])

2.5

In [38]:
bc = [[1,2],[1,4],[3,2],[5,2],[8,9],[10,10]]
labels = np.empty(len(bc))
labels

array([4.24399158e-314, 8.48798316e-314, 4.24399158e-314, 4.24399158e-314,
       1.90979621e-313, 2.12199579e-313])