In [2]:
import numpy as np

In [3]:
b = [[1,2],[1,4],[3,2],[5,2]]
a = np.random.choice(len(b),3,replace = False)
print(a)
c = [b[idx] for idx in a]
c

[0 3 2]


[[1, 2], [5, 2], [3, 2]]

In [10]:
for x,y in enumerate(c):
    print(f"{x}\n{y}")

0
[1, 2]
1
[5, 2]
2
[3, 2]


In [5]:
def dist(x1,x2):
    x1 = np.array(x1)
    x2 = np.array(x2)
    return np.sqrt(np.sum((x1-x2)**2))

dist([4,4],[4,6])

2.0

In [11]:
np.int0(np.zeros((5,2)))

array([[0, 0],
       [0, 0],
       [0, 0],
       [0, 0],
       [0, 0]], dtype=int64)

In [14]:
e = np.array(b)
np.mean(e, axis=0)

array([2.5, 2.5])